
stages:
  - Build
  - Analyze
  - Test

.android_docker_image:
  image: fischerscode/flutter:3.3.2
  tags:
    - proarea-animations
  before_script:
    - flutter clean
    - flutter pub get
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'

.android_key_store:
  extends: .android_docker_image
  before_script:
    - echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > android/key.jks

flutter_analyze:
  extends: .android_docker_image
  stage: Analyze
  script:
    - flutter analyze

flutter_test:
  extends: .android_docker_image
  stage: Test
  script:
    - echo 'Flutter Test'

flutter_build:
  extends: .android_key_store
  stage: Build
  script:
    - flutter build apk
  artifacts:
    paths:
      - "build/app/outputs/apk/release/pro_an_*.apk"
    expire_in: 1 day
