---
variables:
  WEB_HOOK_URL: https://hooks.slack.com/services/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
  MESSAGE_ANALYZE: >-
    {"blocks":[{"type":"divider"},
    {"type":"section","text":{"type":"mrkdwn",
    "text":"*Analyze Complete*

    *Brunch:* $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME $CI_COMMIT_BRANCH

    *Commit:* $CI_COMMIT_TITLE

    *Author:* $GITLAB_USER_NAME

    *Reviewer:* @Temirlan Almassov (edit *.gitlab-ci.yml* to change)

    *MR:* $CI_MERGE_REQUEST_PROJECT_URL"}},
    {"type":"divider"}]}
  MESSAGE_BUILD: >-
    {"blocks":[{"type":"divider"},
    {"type":"section","text":{"type":"mrkdwn",
    "text":"*Build Complete*

    *Brunch:* $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME $CI_COMMIT_BRANCH

    *Commit:* $CI_COMMIT_TITLE

    *Author:* $GITLAB_USER_NAME

    *Reviewer:* @Temirlan Almassov (edit *.gitlab-ci.yml* to change)

    *MR:* $CI_MERGE_REQUEST_PROJECT_URL"}},
    {"type":"divider"}]}


stages:
  - Analyze
  - Test
  - Build
  - Slack Notifications

.job_setting_head:
  image: cirrusci/flutter:latest
  tags:
    - proarea-animations
  before_script:
    - flutter clean
    - flutter pub get
  allow_failure: true

.job_setting_rules_dev:
  extends: .job_setting_head
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'

.job_setting_rules_merge:
  extends: .job_setting_rules_dev
  rules:
    - !reference [.job_setting_rules_dev, rules]
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.needs_analyze:
  needs:
    - job: Flutter analyze
      optional: true

.needs_tests:
  needs:
    - job: Unit tests
      optional: true
    - job: Widget tests
      optional: true
    - job: Integration tests
      optional: true

.needs_build:
  needs:
    - job: Build Android apk
      optional: true
    - job: Build iOS ipa
      optional: true

Flutter analyze:
  # extends: .job_setting_rules_merge
  stage: Analyze
  script:
    # - flutter analyze
    - echo 'analyze - Successfully'

Unit tests:
  extends: .job_setting_rules_dev
  stage: Test
  needs: !reference [.needs_analyze, needs]
  script:
    - echo 'Unit tests - Successfully'

Widget tests:
  extends: .job_setting_rules_dev
  stage: Test
  needs: !reference [.needs_analyze, needs]
  script:
    - echo 'Widget tests - Successfully'

Integration tests:
  extends: .job_setting_rules_dev
  stage: Test
  needs: !reference [.needs_analyze, needs]
  script:
    - echo 'Integration tests - Successfully'

Build Android apk:
  extends: .job_setting_rules_dev
  stage: Build
  needs: !reference [.needs_tests, needs]
  script:
    - flutter build apk
  artifacts:
    paths:
      - "build/app/outputs/apk/release/pro_an_*.apk"
    expire_in: 1 day

Build iOS ipa:
  extends: .job_setting_rules_dev
  stage: Build
  needs: !reference [.needs_tests, needs]
  script:
    - echo 'iOS ipa - Successfully build'

Send notification Analyze:
  stage: Slack Notifications
  extends: .job_setting_rules_merge
  needs: !reference [.needs_analyze, needs]
  script: 
    - echo "Send Slack Messages"
    - 'curl -X POST -H "Content-type: application/json" --data "${MESSAGE_ANALYZE}" $WEB_HOOK_URL'

Send notification Build:
  stage: Slack Notifications
  extends: .job_setting_rules_dev
  needs: !reference [.needs_build, needs]
  script: 
    - echo "Send Slack Messages"
    - 'curl -X POST -H "Content-type: application/json" --data "${MESSAGE_BUILD}" $WEB_HOOK_URL'

