image: fischerscode/flutter:3.3.2

stages:
  - build

before_script:
  - flutter clean
  - flutter pub get

flutter_build:
  tags:
    - 3wella-mobile
  stage: build
  script:
    - flutter analyze
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'
