
stages:
  - Analyze
  # - Test
  - Build

.android_docker_image:
  image: cirrusci/flutter:latest
  tags:
    - proarea-animations
  before_script:
    - flutter clean
    - flutter pub get
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'

# Code format:
#   extends: .android_docker_image
#   stage: Analyze
#   script:
#     - flutter format .

Flutter analyze:
  extends: .android_docker_image
  stage: Analyze
  script:
    - flutter analyze

# Unit tests:
#   extends: .android_docker_image
#   stage: Test
#   script:
#     - echo 'Unit tests - Successfully'

# Widget tests:
#   extends: .android_docker_image
#   stage: Test
#   script:
#     - echo 'Widget tests - Successfully'

# Integration tests:
#   extends: .android_docker_image
#   stage: Test
#   script:
#     - echo 'Integration tests - Successfully'

Build Android apk:
  extends: .android_docker_image
  stage: Build
  script:
    - flutter build apk
  artifacts:
    paths:
      - "build/app/outputs/apk/release/pro_an_*.apk"
    expire_in: 1 day

# Build iOS ipa:
#   extends: .android_docker_image
#   stage: Build
#   script:
#     - echo 'iOS ipa - Successfully build'
