image: fischerscode/flutter:3.3.2

stages:
  - Analyze
  - Test
  - Build

before_script:
  - flutter clean
  - flutter pub get

flutter_analyze:
  tags:
    - proarea-animations
  stage: Analyze
  services:
    - docker:dind
  script:
    - flutter build apk
    - flutter analyze
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'

flutter_test:
  tags:
    - proarea-animations
  stage: Test
  script:
    - echo 'Flutter Test'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'

flutter_build:
  tags:
    - proarea-animations
  stage: Build
  script:
    - flutter build apk
  artifacts:
    paths:
      - "build/app/outputs/apk/release/pro_an_*.apk"
    expire_in: 1 day
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'
