name: proarea_animations
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1+1
  json_annotation: ^4.7.0
  lottie: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.1              
  build_runner: ^2.1.8
  injectable_generator: ^1.5.4
  retrofit_generator: ^4.0.3+2
  json_serializable: ^6.3.2
  flutter_gen_runner: ^5.1.0+1

flutter:
  uses-material-design: true
  
  assets:
    - assets/lottie/