part of '../theme_app.dart';

final _darkThemeData = ThemeData(
  primaryColor: DarkStyleConstants.charcoal,
  unselectedWidgetColor: DarkStyleConstants.charcoalTint3,
  appBarTheme: const AppBarTheme(
    elevation: 0,
    iconTheme: IconThemeData(
      color: DarkStyleConstants.white,
      size: 18,
    ),
    titleTextStyle: TextStyle(
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 20,
      color: DarkStyleConstants.whiteShade,
    ),
    backgroundColor: DarkStyleConstants.charcoal,
  ),
  buttonTheme: ButtonThemeData(
    colorScheme: _colorSchemeDark,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(12),
    ),
  ),
  outlinedButtonTheme: OutlinedButtonThemeData(
    style: OutlinedButton.styleFrom(
      elevation: 4,
      foregroundColor: _colorSchemeDark.primary,
      backgroundColor: _colorSchemeDark.surface,
      side: BorderSide(
        color: _colorSchemeDark.surface,
        width: 0,
      ),
      shadowColor: _colorSchemeDark.background,
      padding: const EdgeInsets.all(20),
      shape: RoundedRectangleBorder(
        side: BorderSide(
          color: _colorSchemeDark.surface,
          width: 0,
        ),
        borderRadius: BorderRadius.circular(12),
      ),
    ),
  ),
  colorScheme: _colorSchemeDark,
  textTheme: const TextTheme(
    headline1: TextStyle(
      fontWeight: FontWeight.w300,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 32,
      height: 36 / 34,
      color: DarkStyleConstants.electricBlueShade,
    ),
    headline2: TextStyle(
      fontWeight: FontWeight.w700,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 30,
      letterSpacing: 32 / 30,
      color: DarkStyleConstants.charcoal,
    ),
    headline3: TextStyle(
      fontWeight: FontWeight.w600,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 28,
      letterSpacing: 30 / 28,
      color: DarkStyleConstants.charcoal,
    ),
    headline4: TextStyle(
      fontWeight: FontWeight.w600,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 26,
      letterSpacing: 28 / 26,
      color: DarkStyleConstants.white,
    ),
    headline5: TextStyle(
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 24,
      letterSpacing: 26 / 24,
      color: DarkStyleConstants.white,
    ),
    headline6: TextStyle(
      fontWeight: FontWeight.w600,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 20,
      height: 24 / 20,
      letterSpacing: .15,
      color: DarkStyleConstants.white,
    ),
    subtitle1: TextStyle(
      fontWeight: FontWeight.w600,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 18,
      height: 24 / 16,
      letterSpacing: .15,
      color: DarkStyleConstants.charcoal,
    ),
    subtitle2: TextStyle(
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 14,
      height: 24 / 14,
      letterSpacing: .1,
      color: DarkStyleConstants.charcoal,
    ),
    bodyText1: TextStyle(
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 16,
      height: 24 / 16,
      letterSpacing: .5,
      color: DarkStyleConstants.charcoal,
    ),
    bodyText2: TextStyle(
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 14,
      height: 20 / 14,
      letterSpacing: .25,
      color: DarkStyleConstants.charcoalTint3,
    ),
    caption: TextStyle(
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 14,
      height: 16 / 12,
      letterSpacing: .25,
      color: DarkStyleConstants.charcoal,
    ),
    button: TextStyle(
      fontWeight: FontWeight.w700,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 16,
      height: 18 / 16,
      letterSpacing: 1.25,
      color: DarkStyleConstants.whiteShade,
    ),
    overline: TextStyle(
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
      fontFamily: 'Manrope',
      fontSize: 10,
      height: 16 / 10,
      letterSpacing: 1.5,
      color: DarkStyleConstants.charcoalTint3,
    ),
  ),
  scaffoldBackgroundColor: DarkStyleConstants.white,
  dividerColor: DarkStyleConstants.charcoal,
  backgroundColor: DarkStyleConstants.white,
  canvasColor: DarkStyleConstants.white,
);

const _colorSchemeDark = ColorScheme(
  brightness: Brightness.dark,
  primary: DarkStyleConstants.charcoal,
  onPrimary: DarkStyleConstants.charcoalTint5,
  primaryContainer: DarkStyleConstants.charcoalTint4,
  onPrimaryContainer: DarkStyleConstants.charcoalTint6,
  secondary: DarkStyleConstants.electricBlue,
  onSecondary: DarkStyleConstants.electricBlueTint,
  secondaryContainer: DarkStyleConstants.electricBlueTint3,
  error: DarkStyleConstants.error,
  onError: DarkStyleConstants.errorTint1,
  background: DarkStyleConstants.whiteShade,
  onBackground: DarkStyleConstants.charcoalTint3,
  surface: DarkStyleConstants.white,
  onSurface: DarkStyleConstants.charcoalTint1,
  surfaceVariant: DarkStyleConstants.charcoalTint2,
  inversePrimary: DarkStyleConstants.aquamarineShade,
  errorContainer: DarkStyleConstants.radical,
  tertiary: DarkStyleConstants.aquamarine,
);
